default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: src_development
  password: google1234
  host: db
  socket: /var/run/mysqld/mysqld.sock
  
development:
  <<: *default
  database: src_development
  port: <%= ENV.fetch('DB_PORT') { 3306 } %>

test:
  <<: *default
  database: src_test
  port: <%= ENV.fetch('DB_PORT') { 3306 } %>

production:
  <<: *default
  database: src_development
  username: src_development
  password: google1234
  host: 172.17.0.1
  port: <%= ENV.fetch('DB_PORT') { 3306 } %>

  
  
  
  
  
  
